--
--
-- 4.1.0 to 4.2.1
--
-- Note: The first released version of CE 4.2 is numbered: 4.2.1
--       (There is no CE 4.2.0)
--
-- There are no database changes between 4.0, 4.1, and 4.2
--
-- This is a dummy placeholder file for the js-upgrade-samedb.sh/bat script
--
