/*
 * Copyright VMware, Inc.
 * SPDX-License-Identifier: GPL-2.0-only
 */
/// <reference path="../../typings-recipe.d.ts" />
/*
 * Remove passwords that were not auto-generated
 */
"use strict";
recipes.register({
    id: "remove-passwords",
    on: { afterFirstboot: {}, afterFailedFirstboot: {} },
    recipeHandler: function (input) {
        // remove app password. If it was autogenerated, it will be stored in the log file
        provisioner.removeAppPassword();
        // remove peer password if it should not be stored
        if (!provisioner.storePeerPassword) {
            provisioner.removePeerPassword();
        }
    }
});
