#!/bin/sh

#
# Start/Stop of JasperReports Server
#

# CHANGE: change line below to point to your jasperserver installation path
JASPER_HOME="/opt/jasperreports-server-4.7" 

# CHANGE: change line below to specify the user that jasperserver will run under
JASPER_USER=username


case "$1" in 
  start) 
    if [ -f $JASPER_HOME/ctlscript.sh ]; then 
      echo "Starting JasperServer" 
      su $JASPER_USER -c "$JASPER_HOME/ctlscript.sh start" 
    fi 
    ;; 
  stop) 
    if [ -f $JASPER_HOME/ctlscript.sh ]; then 
      echo "Stopping JasperServer" 
      su $JASPER_USER -c "$JASPER_HOME/ctlscript.sh stop" 
    fi 
    ;; 
  restart) 
    if [ -f $JASPER_HOME/ctlscript.sh ]; then 
      echo "Restarting JasperServer" 
      su $JASPER_USER -c "$JASPER_HOME/ctlscript.sh restart" 
    fi 
    ;; 
  status) 
    if [ -f $JASPER_HOME/ctlscript.sh ]; then 
      su $JASPER_USER -c "$JASPER_HOME/ctlscript.sh status" 
    fi 
    ;; 
  *) 
    echo $"Usage: $0 {start|stop|restart|status}" 
    exit 1 
    ;; 
esac

:
